### PR TITLE
feat: add --external and --loader support for nodejs_npm_esbuild workflow

### PR DESCRIPTION
**Pull request by chris-armstrong**
Add support for `--loader` and `--external` options to nodejs_npm_esbuild workflow.

This PR replaces #340 and #343, rebased against `develop` as requested.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by moelasmar** [comment]
thanks @chris-armstrong for you contribution. I see you already closed the PR #343, but kept PR #340 open, shall we check both of this PR, and #340 as well?

**Review by moelasmar — CHANGES_REQUESTED** [review]
can you add integration test cases?

**Comment by chris-armstrong** [comment]
> can you add integration test cases?

I've added two new integration tests to cover the options, but the build is failing on all the esbuild integration tests because it can't find the `esbuild` binary. I didn't change this aspect of the tests, so are you able to help in diagnosing what is going on?

**Comment by chris-armstrong** [comment]
> > can you add integration test cases?
> 
> I've added two new integration tests to cover the options, but the build is failing on all the esbuild integration tests because it can't find the `esbuild` binary. I didn't change this aspect of the tests, so are you able to help in diagnosing what is going on?

I'm going to assume the integration tests aren't run every time, and haven't been run for a while, as adding esbuild as a dependency to the one's that didn't have it has fixed the tests

**Comment by moelasmar** [comment]
Thanks @chris-armstrong for the update. I will go through your code, and check the integration test cases.

**Review by mildaniel — APPROVED** [review]

**Review by moelasmar — APPROVED** [review]

**Comment by jfuss** [comment]
@chris-armstrong It doesn't look this this PR has maintainer push access. Could you allow that (I think it is a check mark box on the right side of the page) or update the branch again? I can't merge this in without the branch being updated.

**Comment by chris-armstrong** [comment]
> @chris-armstrong It doesn't look this this PR has maintainer push access. Could you allow that (I think it is a check mark box on the right side of the page) or update the branch again? I can't merge this in without the branch being updated.

I've brought that up to date now @jfuss , I can't find the option to allow updating the branch

**Comment by jfuss** [comment]
@chris-armstrong You might have had to edit the PR. I forget exactly where/how. But thank you for updating the PR and making the contribution.

**Pull request merged**
