### PR TITLE
Esbuild nodejs builder

### PR DESCRIPTION
**Pull request by gojko**
*Issue #, if available:*

Solves the following issues or makes them obsolete
* https://github.com/aws/aws-sam-cli/issues/1446 (bundler supports local symlinks)
* https://github.com/aws/aws-sam-cli/issues/1426 (no need for prepacking any more)
* https://github.com/aws/aws-sam-cli/issues/1544 (bundler will exclude dependencies if not included in the entrypoint)
* https://github.com/aws/aws-sam-cli/issues/2064 (bundler can read outside the code URI as long as it is not running in a docker build)
* https://github.com/aws/aws-sam-cli/issues/2565 (no need for a build script any more to compile tsc)
* https://github.com/aws/aws-sam-cli/issues/2636 (esbuild can directly bundle .ts)
* https://github.com/aws/aws-sam-cli/issues/756 (no need for claudia pack any more)
* https://github.com/aws/aws-sam-cli/issues/3033 (esbuild supports typescript directly)

*Description of changes:*

Support for ESBuild bundler running as part of the Nodejs NPM workflow, providing the following benefits:
1. support for local directory dependencies and NPM7 relative references and sym linked node_modules
2. support for TypeScript transpilation (.ts -> .js)
2. support for minification (smaller bundle sizes)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by falnyr** [comment]
@gojko Hi there, is there any update on this? This would be such a great feature for CDK + Typescript Lambda with SAM. 🙏

**Comment by gojko** [comment]
@falnyr this is waiting on aws people to merge it, @mgrandis will know more

**Comment by kellerkind87** [comment]
@mgrandis or other aws people is there any forcast / outline / perspective to get this merged soon?

**Comment by tostca** [comment]
@mgrandis Is there a possibility to get some more information if this PR will be reviewed in the near future?

**Comment by falnyr** [comment]
Just pinging more AWS folks to see what do we need to make this happen. 🙏 

@aahung @mildaniel

**Comment by mgrandis** [comment]
Yes! So sorry for the late reply!
We are still planning on integrating this, can't give you an exact date but this is on our plate.

**Comment by falnyr** [comment]
@mgrandis any updates? There are conflicts now as this is ready for almost 3 months now.

**Comment by jfuss** [comment]
Closing in favor of #307

**Pull request closed without merging**
