### PR TITLE
feat: Turn esbuild into its own workflow

### PR DESCRIPTION
**Pull request by mildaniel**
*Issue #, if available:*

*Description of changes:*
- Separate out esbuild from the standard Nodejs workflow
- Make workflow choice based on invocation of the builder (can be invoked by Capability("nodejs", "npm-esbuild", None))
- Separate out and fix tests

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by hawflau — APPROVED** [review]

**Comment by hoffa** [comment]
To make reviewing easier, how much of this is just moving things around with minor changes?

**Comment by mildaniel** [comment]
> To make reviewing easier, how much of this is just moving things around with minor changes?

The vast majority is just moving things around from the Node-npm workflow to its own Node-npm-esbuild workflow.

**Comment by hoffa** [comment]
> > To make reviewing easier, how much of this is just moving things around with minor changes?
> 
> The vast majority is just moving things around from the Node-npm workflow to its own Node-npm-esbuild workflow.

Thanks, a few more questions:

1. Why is this change needed?
2. Is this change backwards compatible?

**Comment by mildaniel** [comment]
> > > 
> > 
> > 
> > The vast majority is just moving things around from the Node-npm workflow to its own Node-npm-esbuild workflow.
> 
> Thanks, a few more questions:
> 
>     1. Why is this change needed?
> 
>     2. Is this change backwards compatible?

1. The `esbuild` support changes were initially designed to be a part of the Node workflow. After discussing with the team, the decision was made that it makes more sense for it to be its own workflow, where SAM-CLI makes the decision of when to use `esbuild` instead of Lambda Builders.
2. None of the `esbuild` logic has been released yet, so backward compatibility shouldn't be a concern. The existing Node workflow shouldn't be changed at all.

**Review by hoffa — APPROVED** [review]

**Pull request merged**
